from typing import Dict

import numpy as np

from nvmolkit.types import AsyncGpuResult

def CrossTanimotoSimilarityRawBuffers(fp1: Dict, fp2: Dict, stream: int = 0) -> AsyncGpuResult: ...
def CrossTanimotoSimilarityCPURawBuffers(fp1: Dict, fp2: Dict, stream: int = 0) -> np.ndarray: ...
def CrossCosineSimilarityRawBuffers(fp1: Dict, fp2: Dict, stream: int = 0) -> AsyncGpuResult: ...
def CrossCosineSimilarityCPURawBuffers(fp1: Dict, fp2: Dict, stream: int = 0) -> np.ndarray: ...
