# SPDX-FileCopyrightText: Copyright (c) 2025 NVIDIA CORPORATION & AFFILIATES. All rights reserved.
# SPDX-License-Identifier: Apache-2.0
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
# http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.

"""GPU-accelerated similarity calculations between fingerprints.

This module provides GPU-accelerated implementations of common RDKit operations
found in the DataStructs module, including similarity calculations between fingerprints.
"""
import numpy as np
import torch

from nvmolkit import _DataStructs
from nvmolkit._arrayHelpers import *  # noqa: F403
from nvmolkit.types import AsyncGpuResult

# --------------------------------
# Tanimoto similarity
# --------------------------------

def crossTanimotoSimilarity(fingerprint_group_one: AsyncGpuResult | torch.Tensor,
                            fingerprint_group_two: AsyncGpuResult | torch.Tensor | None = None) -> AsyncGpuResult:
    """Returns the Tanimoto similarity within a set of fingerprints or between two sets of fingerprints.

    Expects fingerprints generated by nvMolKit or as a torch tensor located on device 0, with the leading dimension corresponding to
    the number of fingerprints, and the second dimension representing the packed fingerprint
    bitfield.

    The special case of fingerprint_group_1 as a 1 x n_bits tensor is equivalent to RDKit's BulkTanimotoSimilarity.

    Args:
        fingerprint_group_one: A torch Tensor or AsyncGpuResult computed from nvMolKit fingerprints
        fingerprint_group_two: A torch Tensor or AsyncGpuResult computed from nvMolKit fingerprints,
            or None for all-to-all similarity within fingerprint_group_one.

    Returns:
        An n x m matrix of Tanimoto similarities, with index [i, j] corresponding to the
        similarity between fingerprint i in fingerprint_group_one and fingerprint j in
        fingerprint_group_two. If fingerprint_group_two is None, computes all-to-all
        similarity within fingerprint_group_one.
    """
    bits_two_interface = fingerprint_group_two.__cuda_array_interface__ if fingerprint_group_two is not None else fingerprint_group_one.__cuda_array_interface__
    return AsyncGpuResult(_DataStructs.CrossTanimotoSimilarityRawBuffers(fingerprint_group_one.__cuda_array_interface__,
                                                          bits_two_interface))
def crossTanimotoSimilarityMemoryConstrained(fingerprint_group_one: torch.Tensor,
                                             fingerprint_group_two: torch.Tensor | None = None) -> np.ndarray:
    """Returns the Tanimoto similarity within a set of fingerprints or between two sets of fingerprints.

    Computes results on the GPU, but returns a numpy array on the CPU. Will perform computation in chunks if necessary to avoid running out of memory on the GPU. Will still
    fail if the resulting matrix is too large to fit on the CPU.

    Expects fingerprints generated by nvMolKit or as a torch tensor located on device 0, with the leading dimension corresponding to
    the number of fingerprints, and the second dimension representing the packed fingerprint
    bitfield.

    The special case of fingerprint_group_1 as a 1 x n_bits tensor is equivalent to RDKit's BulkTanimotoSimilarity.

    Args:
        fingerprint_group_one: A torch Tensor or AsyncGpuResult computed from nvMolKit fingerprints
        fingerprint_group_two: A torch Tensor or AsyncGpuResult computed from nvMolKit fingerprints,
            or None for all-to-all similarity within fingerprint_group_one.

    Returns:
        A numpy array of Tanimoto similarities, with index [i, j] corresponding to the similarity between
    """
    bits_two_interface = fingerprint_group_two.__cuda_array_interface__ if fingerprint_group_two is not None else fingerprint_group_one.__cuda_array_interface__
    vals = _DataStructs.CrossTanimotoSimilarityCPURawBuffers(
        fingerprint_group_one.__cuda_array_interface__, bits_two_interface
    )
    # vals is a numpy ndarray with shape (N, M)
    return vals


# --------------------------------
# Cosine similarity
# --------------------------------

def crossCosineSimilarity(fingerprint_group_one: AsyncGpuResult | torch.Tensor, fingerprint_group_two: AsyncGpuResult | torch.Tensor | None = None) -> AsyncGpuResult:
    """Returns the Cosine similarity between two sets of fingerprints.

    Expects fingerprints generated by nvMolKit or as a torch tensor located on device 0, with the leading dimension corresponding to
    the number of fingerprints, and the second dimension representing the packed fingerprint
    bitfield.

    The special case of fingerprint_group_1 as a 1 x n_bits tensor is equivalent to RDKit's BulkCosineSimilarity.

    Args:
        fingerprint_group_one: A torch Tensor computed from nvMolKit fingerprints
        fingerprint_group_two: A torch Tensor computed from nvMolKit fingerprints,
            or None for all-to-all similarity within fingerprint_group_one.

    Returns:
        An AsyncGpuResult object containing the Cosine similarities, with index [i, j] corresponding to the similarity between
        fingerprint i in fingerprint_group_one and fingerprint j in fingerprint_group_two.
    """
    if fingerprint_group_two is not None:
        return AsyncGpuResult(_DataStructs.CrossCosineSimilarityRawBuffers(fingerprint_group_one.__cuda_array_interface__,
                                                              fingerprint_group_two.__cuda_array_interface__))
    return AsyncGpuResult(_DataStructs.CrossCosineSimilarityRawBuffers(fingerprint_group_one.__cuda_array_interface__,
                                                          fingerprint_group_one.__cuda_array_interface__))


def crossCosineSimilarityMemoryConstrained(fingerprint_group_one: torch.Tensor,
                             fingerprint_group_two: torch.Tensor | None = None) -> np.ndarray:
    """Returns the Cosine similarity between two sets of fingerprints.

    Computes results on the GPU, but returns a numpy array on the CPU. Will perform computation in chunks if necessary to avoid running out of memory on the GPU. Will still
    fail if the resulting matrix is too large to fit on the CPU.

    Expects fingerprints generated by nvMolKit or as a torch tensor located on device 0, with the leading dimension corresponding to
    the number of fingerprints, and the second dimension representing the packed fingerprint
    bitfield.

    The special case of fingerprint_group_1 as a 1 x n_bits tensor is equivalent to RDKit's BulkCosineSimilarity.

    Args:
        fingerprint_group_one: A torch Tensor computed from nvMolKit fingerprints
        fingerprint_group_two: A torch Tensor computed from nvMolKit fingerprints,
            or None for all-to-all similarity within fingerprint_group_one.

    Returns:
        A numpy array of Cosine similarities, with index [i, j] corresponding to the similarity between
    """
    bits_two_interface = fingerprint_group_two.__cuda_array_interface__ if fingerprint_group_two is not None else fingerprint_group_one.__cuda_array_interface__
    vals = _DataStructs.CrossCosineSimilarityCPURawBuffers(
        fingerprint_group_one.__cuda_array_interface__, bits_two_interface
    )
    return vals
