# SPDX-FileCopyrightText: Copyright (c) 2025 NVIDIA CORPORATION & AFFILIATES. All rights reserved.
# SPDX-License-Identifier: Apache-2.0
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
# http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.

"""GPU-accelerated similarity calculations between fingerprints.

This module provides GPU-accelerated implementations of common RDKit operations
found in the DataStructs module, including similarity calculations between fingerprints.
"""

import numpy as np
import torch

from nvmolkit import _DataStructs
from nvmolkit._fingerprint_inputs import _prepare_packed_fingerprints
from nvmolkit.types import ArrayInput, AsyncGpuResult

# --------------------------------
# Tanimoto similarity
# --------------------------------


def _fingerprint_inputs(
    fingerprint_group_one: ArrayInput,
    fingerprint_group_two: ArrayInput | None,
    stream: torch.cuda.Stream | None,
) -> tuple[torch.Tensor, torch.Tensor, torch.cuda.Stream]:
    if fingerprint_group_two is None:
        (bits_one,), active_stream = _prepare_packed_fingerprints(
            ("fingerprint_group_one", fingerprint_group_one), stream=stream
        )
        bits_two = bits_one
    else:
        (bits_one, bits_two), active_stream = _prepare_packed_fingerprints(
            ("fingerprint_group_one", fingerprint_group_one),
            ("fingerprint_group_two", fingerprint_group_two),
            stream=stream,
        )
    if bits_one.shape[1] != bits_two.shape[1]:
        raise ValueError("fingerprint_group_one and fingerprint_group_two must have the same feature dimension")
    return bits_one, bits_two, active_stream


def crossTanimotoSimilarity(
    fingerprint_group_one: ArrayInput,
    fingerprint_group_two: ArrayInput | None = None,
    stream: torch.cuda.Stream | None = None,
) -> AsyncGpuResult:
    """Returns the Tanimoto similarity within a set of fingerprints or between two sets of fingerprints.

    Expects fingerprints generated by nvMolKit, a torch tensor, or a numpy array, with the leading dimension corresponding to
    the number of fingerprints, and the second dimension representing the packed fingerprint
    bitfield. CPU tensors and NumPy arrays are copied to CUDA.

    The special case of fingerprint_group_1 as a 1 x n_bits tensor is equivalent to RDKit's BulkTanimotoSimilarity.

    Args:
        fingerprint_group_one: A torch Tensor, numpy.ndarray, or AsyncGpuResult computed from nvMolKit fingerprints
        fingerprint_group_two: A torch Tensor, numpy.ndarray, or AsyncGpuResult computed from nvMolKit fingerprints,
            or None for all-to-all similarity within fingerprint_group_one.
        stream: CUDA stream to use. If None, uses the current stream.

    Returns:
        An n x m matrix of Tanimoto similarities, with index [i, j] corresponding to the
        similarity between fingerprint i in fingerprint_group_one and fingerprint j in
        fingerprint_group_two. If fingerprint_group_two is None, computes all-to-all
        similarity within fingerprint_group_one.
    """
    bits_one, bits_two, active_stream = _fingerprint_inputs(fingerprint_group_one, fingerprint_group_two, stream)
    with torch.cuda.stream(active_stream):
        result = AsyncGpuResult(
            _DataStructs.CrossTanimotoSimilarityRawBuffers(
                bits_one.__cuda_array_interface__, bits_two.__cuda_array_interface__, active_stream.cuda_stream
            )
        )
    result._input_refs = (bits_one, bits_two)
    return result


def crossTanimotoSimilarityMemoryConstrained(
    fingerprint_group_one: ArrayInput, fingerprint_group_two: ArrayInput | None = None
) -> np.ndarray:
    """Returns the Tanimoto similarity within a set of fingerprints or between two sets of fingerprints.

    Computes results on the GPU, but returns a numpy array on the CPU. Will perform computation in chunks if necessary to avoid running out of memory on the GPU. Will still
    fail if the resulting matrix is too large to fit on the CPU.

    Expects fingerprints generated by nvMolKit, a torch tensor, or a numpy array, with the leading dimension corresponding to
    the number of fingerprints, and the second dimension representing the packed fingerprint
    bitfield. CPU tensors and NumPy arrays are copied to CUDA.

    The special case of fingerprint_group_1 as a 1 x n_bits tensor is equivalent to RDKit's BulkTanimotoSimilarity.

    Args:
        fingerprint_group_one: A torch Tensor, numpy.ndarray, or AsyncGpuResult computed from nvMolKit fingerprints
        fingerprint_group_two: A torch Tensor, numpy.ndarray, or AsyncGpuResult computed from nvMolKit fingerprints,
            or None for all-to-all similarity within fingerprint_group_one.

    Returns:
        A NumPy array where element [i, j] is the similarity between fingerprints i and j.
    """
    bits_one, bits_two, active_stream = _fingerprint_inputs(fingerprint_group_one, fingerprint_group_two, None)
    with torch.cuda.stream(active_stream):
        return _DataStructs.CrossTanimotoSimilarityCPURawBuffers(
            bits_one.__cuda_array_interface__, bits_two.__cuda_array_interface__, active_stream.cuda_stream
        )


# --------------------------------
# Cosine similarity
# --------------------------------


def crossCosineSimilarity(
    fingerprint_group_one: ArrayInput,
    fingerprint_group_two: ArrayInput | None = None,
    stream: torch.cuda.Stream | None = None,
) -> AsyncGpuResult:
    """Returns the Cosine similarity between two sets of fingerprints.

    Expects fingerprints generated by nvMolKit, a torch tensor, or a numpy array, with the leading dimension corresponding to
    the number of fingerprints, and the second dimension representing the packed fingerprint
    bitfield. CPU tensors and NumPy arrays are copied to CUDA.

    The special case of fingerprint_group_1 as a 1 x n_bits tensor is equivalent to RDKit's BulkCosineSimilarity.

    Args:
        fingerprint_group_one: A torch Tensor, numpy.ndarray, or AsyncGpuResult computed from nvMolKit fingerprints
        fingerprint_group_two: A torch Tensor, numpy.ndarray, or AsyncGpuResult computed from nvMolKit fingerprints,
            or None for all-to-all similarity within fingerprint_group_one.
        stream: CUDA stream to use. If None, uses the current stream.

    Returns:
        An AsyncGpuResult object containing the Cosine similarities, with index [i, j] corresponding to the similarity between
        fingerprint i in fingerprint_group_one and fingerprint j in fingerprint_group_two.
    """
    bits_one, bits_two, active_stream = _fingerprint_inputs(fingerprint_group_one, fingerprint_group_two, stream)
    with torch.cuda.stream(active_stream):
        result = AsyncGpuResult(
            _DataStructs.CrossCosineSimilarityRawBuffers(
                bits_one.__cuda_array_interface__, bits_two.__cuda_array_interface__, active_stream.cuda_stream
            )
        )
    result._input_refs = (bits_one, bits_two)
    return result


def crossCosineSimilarityMemoryConstrained(
    fingerprint_group_one: ArrayInput, fingerprint_group_two: ArrayInput | None = None
) -> np.ndarray:
    """Returns the Cosine similarity between two sets of fingerprints.

    Computes results on the GPU, but returns a numpy array on the CPU. Will perform computation in chunks if necessary to avoid running out of memory on the GPU. Will still
    fail if the resulting matrix is too large to fit on the CPU.

    Expects fingerprints generated by nvMolKit, a torch tensor, or a numpy array, with the leading dimension corresponding to
    the number of fingerprints, and the second dimension representing the packed fingerprint
    bitfield. CPU tensors and NumPy arrays are copied to CUDA.

    The special case of fingerprint_group_1 as a 1 x n_bits tensor is equivalent to RDKit's BulkCosineSimilarity.

    Args:
        fingerprint_group_one: A torch Tensor, numpy.ndarray, or AsyncGpuResult computed from nvMolKit fingerprints
        fingerprint_group_two: A torch Tensor, numpy.ndarray, or AsyncGpuResult computed from nvMolKit fingerprints,
            or None for all-to-all similarity within fingerprint_group_one.

    Returns:
        A NumPy array where element [i, j] is the similarity between fingerprints i and j.
    """
    bits_one, bits_two, active_stream = _fingerprint_inputs(fingerprint_group_one, fingerprint_group_two, None)
    with torch.cuda.stream(active_stream):
        return _DataStructs.CrossCosineSimilarityCPURawBuffers(
            bits_one.__cuda_array_interface__, bits_two.__cuda_array_interface__, active_stream.cuda_stream
        )
