// SPDX-FileCopyrightText: Copyright (c) 2026 NVIDIA CORPORATION & AFFILIATES. All rights reserved.
// SPDX-License-Identifier: Apache-2.0
//
// Generated by fmcs_occupancy_sweep.py for sm_120. Do not edit.
// Regenerate from the repository root with:
//   python src/mcs/fmcs_cuda/fmcs_occupancy_sweep.py --architectures full --tiers 16 32 64 128 --scratch auto
//   --min-block-size 32 --max-block-size 1024 --block-step 32 --resident-blocks 1 2 --search bisect
//   --reject-stack-spills --config-json src/mcs/fmcs_cuda/fmcs_occupancy_config.json --config-header
//   src/mcs/fmcs_cuda/fmcs_occupancy_config.cuh --production-architecture 120
//
// The generator compiles the real kernel with ptxas and passes its resource
// counts to Nsight Compute's offline OccupancyCalculator. No resident GPU of
// the queried architecture is required.

#ifndef FMCS_CUDA_FMCS_OCCUPANCY_CONFIG_CUH
#define FMCS_CUDA_FMCS_OCCUPANCY_CONFIG_CUH

namespace mcs {
namespace fmcs {

inline constexpr int kFmcsOccupancyTargetArchitecture   = 120;
inline constexpr int kFmcsMaxBlockSizeTwoBlockOccupancy = 352;
inline constexpr int kFmcsMaxBlockSizeSingleOccupancy   = 640;

}  // namespace fmcs
}  // namespace mcs

#endif  // FMCS_CUDA_FMCS_OCCUPANCY_CONFIG_CUH
